In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


In [3]:
print(np.zeros((2,3)))



[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(np.ones((2,3)))



[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(np.full((2,3),7))


[[7 7 7]
 [7 7 7]]


In [8]:

print(np.arange(0, 10, 2))



[0 2 4 6 8]


In [ ]:
print(np.linspace(0, 1, 5))  #dividing into 5 equal parts



[0.   0.25 0.5  0.75 1.  ]


In [11]:
print(np.eye(3))



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [13]:
np.array([1, 2, 3], dtype=float)



array([1., 2., 3.])

In [15]:
arr = np.array([1.5, 2.7, 3.9])

print(arr)


[1.5 2.7 3.9]


In [16]:
print(arr.astype(int))

[1 2 3]
