In [1]:
import numpy as np

In [15]:


arr = np.array([[10, 20, 30],
                [40,50,60],
                [70,80,90]])



In [16]:
print(arr[0, 1])
print(arr[2, 2])



20
90


In [17]:
print(arr[-1,-2])
print(arr[-3, -3])



80
10


In [18]:
# General form: arr[start:stop:step]
print(arr[0:2, 1:3])

print(arr[ :: 2, :: 2]) # every 2nd row & 2nd column



# rows 0-1, cols 1-2

# view (not a copy)

[[20 30]
 [50 60]]
[[10 30]
 [70 90]]


In [ ]:
slice_arr = arr[0, :2]
slice_arr[0] = 999

print(arr[0])



copy_arr = arr[1]. opy()
copy_arr[0] = 555

print(arr[1])

[999  20  30]
[40 50 60]
